# Generated by Django 3.0 on 2021-10-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientvalue',
            name='unique_ingredient',
        ),
    ]
