# Generated by Django 3.0 on 2021-10-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211011_0127'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientvalue',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient'),
        ),
    ]
