# Generated by Django 3.0 on 2021-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210924_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientvalue',
            old_name='value',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
