# Generated by Django 3.0 on 2021-09-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210926_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
    ]
